### ISSUE TITLE
Releases are signed with test-keys

### ISSUE THREAD

**Issue by SebiderSushi** [Loup-ROM/android#2]
For more information, refer to https://wiki.lineageos.org/signing_builds.html

As far as i know, this mainly concerns the key which is used to sign all system applications.
Since the test-keys are public, anyone is able to craft apks which are signed in a way so that they can be installed as an upgrade to a system application. This can be used to hijack application data as well as system app permissions.

Because of this, production builds should be signed with secret keys known only to the maintainer.

**Comment by bitrvmpd** [comment]
It's not an official lineage build. Also for your consideration: If I wanted to I could include malicious software either way (you're using a rom builded by anyone on the internet).

So what's the point of this issue? :| 

Do you want this rom builded against private keys?

**Comment by SebiderSushi** [comment]
Yes, test-keys & private keys are irrelevant to the question of whether you trust the maintainer.

I am aware that developer keys just protect against the possibility of accidentally sideloading a malicious application crafted by anyone else.

Since this is a very stable build of LineageOS it can be suitable for some less tech savvy users which might be susceptible so such an attack.

I just posted the issue to find out whether you know about the topic, how you assess the situation and which stance you take on the subject and for which reason you decide to use test-keys for signing. If it is not too much additional effort to use developer keys (e.g. caused by a more complicated build setup) i don't see why developer keys should not be used opportunistically to whatever extent possible - which is why i assume that maintainers who use test-keys are probably unaware of the subject.

**Comment by bitrvmpd** [comment]
The main issue would be that it would break OTA updates (no matching keys). And will require a full wipe to "upgrade". 

I don't think those less tech savvy users wanted to wipe everything to stay up to date...

That's why I don't use my own keys :). I know it's unsafe and was my mistake for not doing it from the start.

But that's why Stock ROMs exists.

**Comment by SebiderSushi** [comment]
> The main issue would be that it would break OTA updates (no matching keys). And will require a full wipe to "upgrade".

The LineageOS Wiki article i linked contains a section on how to migrate keys on existing installs without wiping data.

**Comment by bitrvmpd** [comment]
@_@ is not a seamless or secure process anyway:

![Screenshot_20200520-135112~2](https://user-images.githubusercontent.com/654296/82485653-626dda00-9aa1-11ea-9ce8-493585f74c9c.png)

**Comment by SebiderSushi** [comment]
The second method with the script sounds reasonable. It is limited to one direction. It can optionally be done behind the scenes by some updates, or by releasing a standalone migration script.

I am not trying to convince you at all costs. You are providing these build free of charge, without any kind of contract. You can do what you want.
However, if you decide to keep signing with private keys, i would be very interested in the motives and considerations behind it.

**Comment by bitrvmpd** [comment]
I'm locking this thread. The answer you are looking for is at my first response.

> It's not an official lineage build.(...)

Cheers.
